language: node_js
sudo: required
dist: trusty
node_js:
  - 6
  - 7
matrix:
  allow_failures:
    - node_js: 6
os:
  - linux
env:
  - NODE_ENV=travis CXX="g++-4.8" CC="gcc-4.8"
services:
  - mongodb
addons:
  ssh_known_hosts: "$SERVER"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - clang
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_43bc1b2769ac_key -iv $encrypted_43bc1b2769ac_iv
    -in deploy_key.enc -out deploy_key -d
  - npm i nsp -g
  - npm i snyk -g
  - npm install -g @angular/cli
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sleep 3
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_key
  - ssh-add $TRAVIS_BUILD_DIR/deploy_key
before_script:
#  - snyk auth $SNYK_TOKEN
#  - snyk test
script: 
  - node_modules/karma/bin/karma start karma.conf.js --single-run
after_script:
  - nsp check
  - snyk test
#  - gulp test:coverage
#  - node_modules/.bin/lcov-result-merger 'coverage/**/lcov.info' | node_modules/coveralls/bin/coveralls.js
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r -e "ssh -p $SSH_PORT -o StrictHostKeyChecking=no" --exclude='logs/app.log' --delete-after
    --quiet $TRAVIS_BUILD_DIR/ $USER@$SERVER:$DEPLOY_PATH
  on:
    branch: master
    node: '7.x'
- provider: script
  skip_cleanup: true
  script: ssh -p $SSH_PORT $USER@$SERVER -o StrictHostKeyChecking=no "cd $DEPLOY_PATH
    && npm run prod && pm2 restart all"
  on:
    branch: master
    node: '7.x'
