language: node_js
sudo: false
node_js:
- 6
- 7
matrix:
  allow_failures:
  - node_js: 6
os:
- linux
- centos
- macosx
- windows
env:
- NODE_ENV=travis CXX="g++-4.8" CC="gcc-4.8"
services:
- mongodb
addons:
  ssh_known_hosts: "$SERVER"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - clang
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_43bc1b2769ac_key -iv $encrypted_43bc1b2769ac_iv
  -in deploy_key.enc -out deploy_key -d
- npm i nsp -g
- npm i snyk -g
- npm install -g @angular/cli
- npm install -g firebase-tools
- npm install protractor
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- node_modules/protractor/bin/webdriver-manager update --standalone --firefox
- node_modules/protractor/bin/webdriver-manager start 2>&1 &
- sleep 3
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_key
- ssh-add $TRAVIS_BUILD_DIR/deploy_key
before_script: 
script:
- npm run prod
after_script:
- nsp check
- gulp test:coverage
- node_modules/.bin/lcov-result-merger 'coverage/**/lcov.info' | node_modules/coveralls/bin/coveralls.js
after_success:
- firebase deploy --token $FIREBASE_TOKEN
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r -e "ssh -p $SSH_PORT -o StrictHostKeyChecking=no" --exclude='logs/app.log'
    --delete-after --quiet $TRAVIS_BUILD_DIR/ $USER@$SERVER:$DEPLOY_PATH
  on:
    branch: master
    node: 7.x
- provider: script
  skip_cleanup: true
  script: ssh -p $SSH_PORT $USER@$SERVER -o StrictHostKeyChecking=no "cd $DEPLOY_PATH
    && npm run prod && pm2 restart all"
  on:
    branch: master
    node: 7.x
notifications:
  webhooks:
    urls:
    - "$GITTER_IM_URL"
    on_success: change
    on_failure: always
    on_start: never
